DROP DATABASE IF EXISTS iot;

CREATE DATABASE IF NOT EXISTS iot;

USE iot;

CREATE TABLE IF NOT EXISTS probes (
    id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    probeName VARCHAR(100) NOT NULL,
    ip VARCHAR(100) NOT NULL,
    latitude FLOAT NOT NULL,
    longitude FLOAT NOT NULL
);

CREATE TABLE IF NOT EXISTS readings (
    id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    probeId INT NOT NULL,
    temperature INT NOT NULL,
    humidity INT NOT NULL,
    readingDate DATETIME
);

CREATE TABLE IF NOT EXISTS users (
  id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  psw VARCHAR(20) NOT NULL,
  firstName VARCHAR(20) NOT NULL,
  fullName VARCHAR(20) NOT NULL,
  mail VARCHAR(80) NOT NULL
);